--Query5 
--A) Using A division query

SELECT c.CustomerId, c.CustomerName
FROM SQLPlayground.dbo.Customer AS C, SQLPlayground.dbo.Purchase AS PS 
-- TABLE A, target
WHERE NOT EXISTS
(
	SELECT * 
	FROM SQLPlayground.dbo.Product AS P-- TABLE B, other side of the relationship
	WHERE NOT EXISTS
	(
		SELECT *
		FROM SQLPlayground.dbo.Purchase AS Pu	--  TABLE AB, the one generated by the relationship
		WHERE Pu.CustomerID = C.CustomerID
		AND	Pu.ProductID = P.ProductID 	
	)	
)
AND c.CustomerID = PS.CustomerID 
Group by c.CustomerId, c.CustomerName
HAVING SUM(PS.Qty) >= 50

--B) Using Having Clause

SELECT p.CustomerId, c.CustomerName
FROM SQLPlayground.dbo.Purchase as p
JOIN SQLPlayground.dbo.Customer as c 
ON p.CustomerId = c.CustomerId
GROUP BY p.CustomerId, c.CustomerName
HAVING 
COUNT(DISTINCT ProductId) = (SELECT COUNT(*)
FROM SQLPlayground.dbo.Product as pr) 
AND SUM(Qty) >= 50


